### ISSUE TITLE
How do I call an API in a factory definition?

### ISSUE THREAD

**Issue by uchagani** [thoughtbot/fishery#26] opened 2020-06-10 01:13 UTC
One of my properties depends on fetching a value from an API.  How can that be accomplished?

**Comment by stevehanson** [comment] 2020-06-12 01:22
`facotry.build()` is not asynchronous, so there is not a way to achieve this currently out of the box. We are working on adding an asynchronous `create` method in #16 which could work for your situation once we finish implementing it.

**Comment by stevehanson** [comment] 2020-07-06 20:30
I'm going to close this as a duplicate of #16.

**Closed by stevehanson** 2020-07-06 20:30 UTC
